flickit-platform/flickit-assessment

.github/workflows/build-docker-image.yml, pom.xml
Close [FAC-8](https://issue.asta.ir/browse/FAC-8)
=> OTAT-527:feature:Add jib plugin

src/main/java/org/flickit/flickitassessmentcore/adapter/in/rest/answer/SubmitAnswerRequestDto.java, src/main/java/org/flickit/flickitassessmentcore/adapter/in/rest/answer/SubmitAnswerRestController.java, src/main/java/org/flickit/flickitassessmentcore/adapter/out/persistence/answer/AnswerJpaEntity.java, src/main/java/org/flickit/flickitassessmentcore/adapter/out/persistence/answer/AnswerMapper.java, src/main/java/org/flickit/flickitassessmentcore/application/port/in/answer/SubmitAnswerUseCase.java, src/main/java/org/flickit/flickitassessmentcore/application/port/out/answer/CreateAnswerPort.java, src/main/java/org/flickit/flickitassessmentcore/application/service/answer/SubmitAnswerService.java, src/main/java/org/flickit/flickitassessmentcore/common/ErrorMessageKey.java, src/main/java/org/flickit/flickitassessmentcore/domain/Answer.java, src/main/resources/i18n/messages_en.properties, src/main/resources/liquibase/changelog-0.1.xml, src/main/resources/liquibase/changelog-0.2.xml, src/main/resources/postman/flickit-assessment-core.postman_collection.json, src/test/java/org/flickit/flickitassessmentcore/application/service/answer/SubmitAnswerServiceTest.java
Close [FAC-33](https://issue.asta.ir/browse/FAC-33)
=> FAC-33:feature:Add questionnaireId to Answers

pom.xml
Close [FAC-26](https://issue.asta.ir/browse/FAC-26)
=> FAC-26:fix:Fix sonar coverage report

src/main/java/org/flickit/flickitassessmentcore/adapter/in/rest/evidence/GetEvidenceListRestController.java, src/main/java/org/flickit/flickitassessmentcore/adapter/out/persistence/evidence/EvidenceJpaRepository.java, src/main/java/org/flickit/flickitassessmentcore/adapter/out/persistence/evidence/EvidencePersistenceJpaAdaptor.java, src/main/java/org/flickit/flickitassessmentcore/application/port/in/evidence/GetEvidenceListUseCase.java, src/main/java/org/flickit/flickitassessmentcore/application/port/out/evidence/LoadEvidencesByQuestionAndAssessmentPort.java, src/main/java/org/flickit/flickitassessmentcore/application/service/evidence/GetEvidenceListService.java, src/main/java/org/flickit/flickitassessmentcore/common/ErrorMessageKey.java, src/main/resources/i18n/messages_en.properties, src/main/resources/postman/flickit-assessment-core.postman_collection.json, src/test/java/org/flickit/flickitassessmentcore/application/service/evidence/GetEvidenceListServiceTest.java
Close [FAC-41](https://issue.asta.ir/browse/FAC-41)
=> FAC-41:feature:Add assessmentId to loadEvidenceService filters

src/main/java/org/flickit/flickitassessmentcore/application/port/in/assessment/GetAssessmentListUseCase.java
Change lastModificationDate to lastModificationTime
=> FAC:fix:Refactor GetAssessmentListUseCase

src/main/java/org/flickit/flickitassessmentcore/adapter/out/persistence/answer/AnswerJpaRepository.java, src/main/java/org/flickit/flickitassessmentcore/adapter/out/persistence/answer/AnswerMapper.java
Closes [FAC-76](https://issue.asta.ir/browse/FAC-76)
=> FAC-76: Edit answer related services due to notApplicable fields

src/main/java/org/flickit/flickitassessmentcore/application/domain/ConfidenceLevel.java
Closes [FAC-84](https://issue.asta.ir/browse/FAC-84)
=> FAC-84: Create ConfidenceLevel Enum

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answer/GetAnswerListUseCase.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/GetAnswerListServiceTest.java
Closes [FAC-90](https://issue.asta.ir/browse/FAC-90)
=> FAC-90: Add ConfidenceLevel to answer list

flickit-assessment-data/src/main/resources/liquibase/changelog-0.6.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.7.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml, flickit-assessment-data/src/main/resources/liquibase/properties.xml
=> FAC-96:feature:Create django tables by liquibase

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadSubjectReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/SubjectReport.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subject/ReportSubjectService.java
Closes [FAC-89](https://issue.asta.ir/browse/FAC-89)
=> FAC-89: Add confidence value to subject report output

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadSubjectReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/SubjectReport.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subject/ReportSubjectService.java
Reverts avansoft/flickit-assessment#90
=> Revert "FAC-89: Add confidence value to subject report output"

.github/workflows/migration_ci-cd.yml
=> FAC-102:feature:Add ci-cd to migration branch

pom.xml
Ficx docker image source label
=> Migration:fix:Change docker image source label to flickit-assessment

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadSubjectReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/SubjectReport.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subject/ReportSubjectService.java
Reverts avansoft/flickit-assessment#92
=> Revert "Revert "FAC-89: Add confidence value to subject report output""

flickit-assessment-data/src/main/resources/liquibase/changelog-0.8.xml
Closes [FAC-122](https://issue.asta.ir/browse/FAC-122)
=> FAC-122: Add default value for null confidence levels

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentListUseCase.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentListItemView.java
=> FAC-143:feature:Add isConfidenceValid to AssessmentListItem

flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/validate/impl/QuestionnaireUpdateKitValidatorTest.java
Closes [FAC-119](https://issue.asta.ir/browse/FAC-119)
=> FAC-119: Create questionnaire validator test

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/jwt/UserContext.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/MissingAuthorizationHeaderException.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/api/ErrorCodes.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/MissingAuthorizationHeaderExceptionHandler.java, flickit-assessment-common/src/main/resources/i18n/messages_en.properties
=> FAC-159:fix:Return 401 error on missing authorization header

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaEntity.java
Changed the column names and methods in various classes to track the users who created and last modified the data. This update improves the auditing of changes made to the data and provides a more precise user activity tracking. The affected classes include AttributeJpaEntity, EvidenceJpaEntity, EvidenceJpaRepository, and EvidenceMapper.
=> FAC-199 Bug:Update column names and methods for user tracking

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
=> FAC-266:fix:Fix answered questions count on subject progress service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/rest/answeroption/AnswerOptionRestAdapter.java
=> FAC-296:fix:Filter not null ids

flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/RuntimeExceptionHandler.java
=> FAC-308:fix:Capture exception with sentry in RuntimeExceptionHandler

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitlike/KitLikeJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitlike/KitLikeJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.17.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-323:feature:Refactor KitLike table

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.28.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.29.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/constraint/AssessmentUsersDataConstraintErrorMapper.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpaceMapper.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/DeleteSpacePort.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/constant/ExpertGroupConstants.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/constant/SpaceConstants.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/DeleteSpaceService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/DeleteSpaceServiceTest.java
=> Fac 598 fix bug deleted space used in title uniqueness

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.27.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.29.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-594 Create assessment insight table and entity

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.29.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-595:feature:Add subject insight table

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/messages_en.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/CreateAssessmentInsightRequestDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/CreateAssessmentInsightResponseDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/CreateAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinsight/AssessmentInsightMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinsight/AssessmentInsightPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentInsight.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/CreateAssessmentInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinsight/CreateAssessmentInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinsight/LoadAssessmentInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinsight/UpdateAssessmentInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/CreateAssessmentInsightUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaRepository.java
=> FAC-599: Create and Edit Assessment Insight

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/CreateAssessmentInsightResponseDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/CreateAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/CreateAssessmentInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/CreateSubjectInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightServiceTest.java
=> FAC-610: Refactor - Remove return type from usecase

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentanalysis/AssessmentAnalysisJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.29.xml
=> FAC-606 Create assessment analysis jpa entity & table

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
=> FAC-612:fix:Return null for confidence value to users without permission

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
=> FAC-617: Change EXPORT_ASSESSMENT_REPORT Permission from ASSESSOR to VIEWER Role

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/notification/NotificationEnvelope.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/novu/CreateAssessmentNovuRequestConverter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/novu/GrantAssessmentUserRoleNovuRequestConverter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/novu/SubmitAnswerNovuRequestConverter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/novu/SubmitAnswerNovuRequestConvertor.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/notification/SubmitAnswerNotificationCreator.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationCreator.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/notification/GrantAssessmentUserRoleNotificationCreator.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
=> FAC-619:feature:Add title to notifications payload

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
=> FAC-624: Add VIEW_ASSESSMENT_QUESTIONNAIRE_LIST to Viewer role

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceListUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListServiceTest.java
=> FAC-620: Add Editable and Deletable Fields to Items in `evidenceList`

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java
=> FAC-623 Refactor GetAttributeInsightService & its tests

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java
=> FAC-585 Check All questions have been answered before Ai insight creation

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advice/PlanConstraintProvider.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advice/PlanConstraintProviderMultipleTargetTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advice/PlanConstraintProviderTest.java
=> FAC-621:fix:Add SOFT_SCORE_FACTOR to PlanConstraintProvider

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppAiProperties.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AssessmentCommonAutoConfig.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/DefaultChatOptions.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/openai/OpenAiAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java, flickit-assessment-server/src/main/resources/application-dev.properties, pom.xml
=> FAC-622: Use Spring AI in Attribute AI Insight Service

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
=> FAC-616:fix:Fix subject default insight

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
=> FAC-631:fix:Check assessment existence in CheckAssessmentSpaceMemberhipPort

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentanalysis/AddAssessmentAnalysisInputFileRequestDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentanalysis/AddAssessmentAnalysisInputFileRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/minio/MinioAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentanalysis/AssessmentAnalysisMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentanalysis/AssessmentAnalysisPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnalysisType.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentAnalysis.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentanalysis/AddAssessmentAnalysisInputFileUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentanalysis/CreateAssessmentAnalysisPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentanalysis/LoadAssessmentAnalysisPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentanalysis/UpdateAssessmentAnalysisInputPathPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/minio/DeleteEvidenceAttachmentFilePort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/minio/DeleteFilePort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/minio/UploadAssessmentAnalysisInputFilePort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentanalysis/AddAssessmentAnalysisInputFileService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidenceattachment/DeleteEvidenceAttachmentService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnalysisTypeTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentanalysis/AddAssessmentAnalysisInputFileUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentanalysis/AddAssessmentAnalysisInputFileServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidenceattachment/DeleteEvidenceAttachmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentAnalysisMother.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentanalysis/AssessmentAnalysisJpaRepository.java
=> FAC-607:feature:Add AddAssessmentAnalysisInputFileUseCase

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/UpdateAttributeInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/UpdateAttributeInsightUseCaseParamTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC-600: Implement Assessor Insight Limitation in UpdateAttributeInsight

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCaseParamTest.java
=> FAC-637: Fix Error Message on Empty Short Title During Assessment Creation

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/advicenarration/GetAdviceNarrationUseCase.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationService.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationServiceTest.java
=> FAC-641:feature:Add aiEnabled to GetAdviceNarrationUseCase.Result

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java, flickit-assessment-common/src/main/resources/i18n/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvite/InviteAssessmentUserService.java, flickit-assessment-server/src/main/resources/application-dev.properties, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/InviteExpertGroupMemberService.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/spaceuseraccess/InviteSpaceMemberService.java
=> FAC-604: add support email to emails

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
=> FAC-638:fix:Fix confidence value in insight

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/advicenarration/CreateAiAdviceNarrationRequestDto.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/advicenarration/CreateAiAdviceNarrationRestController.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/advicenarration/AdviceNarrationPersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/attribute/AttributeMapper.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/AssessmentResult.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/Attribute.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/MaturityLevel.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAiAdviceNarrationUseCase.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/advicenarration/UpdateAdviceNarrationPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/atribute/LoadAttributesPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/maturitylevel/LoadMaturityLevelsPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAdviceAiAiNarrationService.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAdviceAiNarrationService.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationService.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAiAdviceNarrationUseCaseParamTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAdviceAiNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAssessorAdviceNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationServiceTest.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java, flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/advicenarration/AdviceNarrationJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.32.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-639: Edit generate advice prompt and service

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.32.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/CreateSubjectRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/CreateSubjectResponseDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/CreateSubjectRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Subject.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/CreateSubjectUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/CreateSubjectPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/CreateSubjectService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/subject/CreateSubjectUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/CreateSubjectServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> Merge Dev repo

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAssessorAdviceNarrationUseCase.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAssessorAdviceNarrationUseCaseParamTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAssessorAdviceNarrationServiceTest.java, flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
=> FAC-639: increase advice size limit in use case

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/advicenarration/AdviceNarrationJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.32.xml
=> FAC-639: Increase assessor_narration column limit size to 1500 in db

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
=> FAC-648:fix:Remove subject-default-insight duplication

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/levelcompetence/DeleteLevelCompetenceRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/LevelCompetencePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/levelcompetence/DeleteLevelCompetenceUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/levelcomptenece/DeleteLevelCompetencePort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/levelcompetence/DeleteLevelCompetenceService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/levelcompetence/UpdateLevelCompetenceService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/levelcompetence/DeleteLevelCompetenceUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/levelcompetence/DeleteLevelCompetenceServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/levelcompetence/UpdateLevelCompetenceServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-653 Imp delete level competence service

dev/dsl-parser/docker-compose.yml, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.33.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/LevelCompetencePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
[] - Did you add the Confluence's link to the Jira task as a description?
=> FAC-660:feature:Change level competence pk

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessment/AssessmentMapper.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/Assessment.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/assessment/LoadAssessmentPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationService.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AssessmentMother.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java, flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
=> FAC-661: Improve advice narration prompt

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/users/user/UserMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitUserListUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/LoadKitUsersPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitUserListService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitUserListUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitUserListServiceTest.java
=> FAC-668: change get assessment kit users service output

flickit-assessment-data/src/main/resources/liquibase/changelog-0.33.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitServiceTest.java
=> FAC-669:fix:Fix not access to old private kits

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/KitWithDraftVersionIdView.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetExpertGroupKitListUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetExpertGroupKitListService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitStatsService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/AttributeUpdateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionnaireUpdateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectQuestionnaireUpdateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectUpdateKitPersister.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/AttributeUpdateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionnaireUpdateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectQuestionnaireUpdateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectUpdateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
=> FAC-666:feature:Add draftVersionId to GetExpertGroupKitListService output

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitversion/ActivateKitVersionRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitversion/ActivateKitVersionUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitversion/ActivateKitVersionUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-665:feature:Impl ActivateKitVersionService

flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java, flickit-assessment-common/src/main/resources/i18n/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvite/InviteAssessmentUserService.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/InviteExpertGroupMemberService.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/MessageKey.java
=> FAC-680: Add support email at the end of email bodies conditionally

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java
=> FAC-680: Make supportEmail property optional

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/DeleteSubjectRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/DeleteSubjectUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/DeleteSubjectPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/DeleteSubjectService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/subject/DeleteSubjectUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/DeleteSubjectServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/KitVersionMother.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-659: Implement Delete Subject Service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/InvalidateAssessmentResultCalculatePort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/InvalidateAssessmentResultConfidencePort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/InvalidateAssessmentResultPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentresult/AssessmentResultJpaRepository.java
=> FAC-688:fix:Fix isCalculateValid bug in SubmitAnswerService

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/UpdateSubjectOrdersRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/UpdateSubjectOrdersRestController.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-647: Rename request dto record

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/DeleteAttributeRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/DeleteAttributeUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/DeleteAttributePort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/DeleteAttributeService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/DeleteAttributeUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/DeleteAttributeServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/KitVersionMother.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-658 Impl delete attribute service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroptionimpact/AnswerOptionImpactMapper.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/OptionImpactWithQuestionImpactView.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeLevelQuestionsDetailService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeLevelQuestionsDetailServiceTest.java
=> FAC-693: remove ralation of answer option impact and question impact

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/DeleteQuestionRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/DeleteQuestionUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/DeleteQuestionPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/DeleteQuestionService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/question/DeleteQuestionUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/DeleteQuestionServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-645 Impl delete question service

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
=> FAC-273:feature:Incorporate advisable in advice

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitStatsService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitStatsServiceTest.java
=> FAC-698: Fix nullPointerException When ActiveKitversion is null in kitStats Service

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitversion/GetKitVersionIdRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitversion/GetKitVersionRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitversion/GetKitVersionUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/GetKitVersionService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitversion/GetKitVersionUseCaseTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/GetKitVersionServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-700: Implement Load Kit Version Service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
=> FAC-273:feature:Move advisable condition

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-data/src/main/resources/liquibase/changelog-0.34.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
=> FAC-697:feature:Add unique constraint to fak_question_impact

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
=> FAC-706: Fix bug in parameter setting of updateQuestion param

flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/DeprecatedVersionException.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/api/ErrorCodes.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/DeprecatedVersionExceptionHandler.java, flickit-assessment-common/src/main/resources/i18n/messages_en.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/internal/ValidateAssessmentResult.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/internal/ValidateAssessmentResultTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
=> FAC-704:feature:Add kit version validation to ValidateAssessmentResult service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/seq/KitDbSequenceGenerators.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.35.xml
=> FAC-708: Feat - Create `AnswerRange` Table

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
=> FAC-717: Fix NPE in loadSpaceAssessments

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeValue.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectValue.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentResultTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AttributeValueTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/SubjectValueTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeValueMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectValueMother.java
=> FAC-713: Improve Maturity Level Calculation

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
…tities` of `loadByKitVersionId` Function of `SubjectPersistenceJpaAdapter`
=> FAC-721: fix - Fix getKitStat bug in Case of Subjects Without Atrributes

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/GetQuestionnaireQuestionsRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/GetQuestionnaireQuestionsUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionnaireQuestionsPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/question/GetQuestionnaireQuestionsUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-718 Impl get questionnaire's questions service

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AnswerOption.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answeroption/GetQuestionOptionsUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersister.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerOptionMother.java
=> FAC-723: Add `value` Parameter to GetQuestionOptions api

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answerrange/UpdateAnswerRangeRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answerrange/UpdateAnswerRangeRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answerrange/UpdateAnswerRangeUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/UpdateAnswerRangePort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/UpdateAnswerRangeService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/answerrange/UpdateAnswerRangeUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/UpdateAnswerRangeServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-720 Impl update answer range service

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroptionimpact/CreateAnswerOptionImpactPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactServiceTest.java
=> FAC-733 Add option impacts when creating a question impact

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroptionimpact/CreateAnswerOptionImpactPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactServiceTest.java
Reverts flickit-platform/flickit-assessment#448
=> Revert "FAC-733 Add option impacts when creating a question impact"

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/dsl/QuestionDslModel.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionService.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-726: Add `AnswerRangeId` As anNullable Parameter to Update question api

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionServiceTest.java
When activating a kitVersion, its corresponding kit's lastMajorModificationTime updated.
=> FAC-729 Update lastMajorModificationTime

flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectInsightMother.java
=> FAC-696: Solving the non-determinism in testing

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValueMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValuePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentResult.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeValue.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Subject.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectValue.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentResultTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/SubjectValueTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeValueMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectValueMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.35.xml
=> FAC-423: Change assessment calculation algorithm

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answerrange/GetAnswerRangeListUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/GetAnswerRangeListService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsServiceTest.java
=> FAC-739: Test - Add `value` to `AnswerOptionListItem`

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
=> FAC-745: Fix Duplicate Items in Questionnaire Subjects

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
Return empty list in load answerOptions for question with null answerRangeId
=> FAC-746:fix:Fix NPE in GetQuestionOptionsService

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
=> FAC-749 Fix NPE when loading answer ranges

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advice/CreateAdviceService.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
=> FAC-748:fix:Remove query that causes conflicts with multiple KitVersions

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java
=> FAC-751:feature:Prevent question update when answer range id changes

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
=> FAC-756 Change way of finding the assessment maturity level

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java
=> FAC-757: Add null check to handle subject without attribute

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/DefaultChatOptions.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java
=> FAC-723: Improve Attribute AI Insight Prompt

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributevalue/CreateAttributeValuePort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.36.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-763:fix:Change CreateAttributeValuePort method parameter to set

flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/CreateExpertGroupScenarioTest.java
=> FAC-759: feat - Complete CreateExpertGroupScenarioTest for Repetitive Title

flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/DeleteExpertGroupMemberService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/DeleteExpertGroupMemberServiceTest.java
=> FAC-772: fix - Prevent expert group member service owner deletion

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
=> FAC-753:improve:Improve advice plan creation

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/CreateKitCustomRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/CreateKitCustomRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/UpdateKitCustomRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/UpdateKitCustomRestController.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> Fac 787: move kitId from path param to body

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.36.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.37.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
=> FAC-781: Ensure KitVersion Status uniqueness

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
=> FAC-788 Fix ordering issue in get kit custom subjects service

flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroupaccess/ExpertGroupAccessJpaRepository.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroupaccess/LeaveExpertGroupRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroupaccess/ExpertGroupAccessMapper.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroupaccess/ExpertGroupAccessPersistenceJpaAdapter.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/ExpertGroupAccess.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/ExpertGroupAccessStatus.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroupaccess/LeaveExpertGroupUseCase.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/ConfirmExpertGroupInvitationService.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/LeaveExpertGroupService.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/expertgroupaccess/LeaveExpertGroupUseCaseParamTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/ConfirmExpertGroupInvitationServiceTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/LeaveExpertGroupServiceTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/UpdateExpertGroupLastSeenServiceTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/test/fixture/application/ExpertGroupAccessMother.java, flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
=> FAC:771- Implement LeaveExpertGroup Service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/kitcustom/KitCustomPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/internal/ValidateAssessmentResult.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/kitcustom/LoadKitCustomLastModificationTimePort.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/internal/ValidateAssessmentResultTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/MigrateAssessmentResultKitVersionServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentanalysis/AddAssessmentAnalysisInputFileServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/UpdateAttributeInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/CreateSubjectInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitcustom/KitCustomJpaRepository.java
=> Fac 806: refactor validate assessment result to consider kitcustom

flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/user/UserJpaRepository.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/UpdateUserProfilePictureRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/minio/MinioAdapter.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/user/UserPersistenceJpaAdapter.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/user/UpdateUserProfilePictureUseCase.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/user/UpdateUserPicturePort.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/user/UploadUserProfilePicturePort.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/user/UpdateUserProfilePictureService.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/user/UpdateUserProfilePictureUseCaseParamTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/user/GetUserProfileServiceTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/user/UpdateUserProfilePictureServiceTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/test/fixture/application/UserMother.java, flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
=> FAC-501: Update user profile picture

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/CreateAdviceItemRequestDto.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/CreateAdviceItemRestController.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/GetAdviceItemListRestController.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/UpdateAdviceItemRestController.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/adviceitem/AdviceItemPersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/AssessmentResult.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/UpdateAdviceItemUseCase.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/adviceitem/LoadAdviceItemPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/adviceitem/UpdateAdviceItemPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/assessmentresult/LoadAssessmentResultPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/UpdateAdviceItemService.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/adviceitem/UpdateAdviceItemUseCaseParamTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/CreateAdviceItemServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemListServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/UpdateAdviceItemServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAssessorAdviceNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AssessmentResultMother.java, flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json, flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
=> FAC-808: Modify AdviceItemServiceAddresses

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/CreateAdviceItemService.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/UpdateAdviceItemService.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/CreateAdviceItemServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/UpdateAdviceItemServiceTest.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
=> FAC- 809: Add MANAGE_ADVICE_ITEM Permission

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/GetAdviceItemPriorityLevelsRestController.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/PriorityLevel.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemPriorityLevelsUseCase.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemPriorityLevelsService.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/domain/adviceitem/PriorityLevelTest.java, flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json, flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
=> FAC-804: Implement GetPriorityLevels service

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/GetAdviceItemImpactLevelsRestController.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/ImpactLevel.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemImpactLevelsUseCase.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemImpactLevelsService.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/domain/adviceitem/ImpactLevelTest.java, flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json, flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
=> FAC-803: Implement GetAdviceImpactLevels service

dev/dsl-parser/docker-compose.yml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangeMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AnswerRange.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/dsl/AnswerRangeDslModel.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/dsl/AssessmentKitDslModel.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/dsl/QuestionDslModel.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/CreateAnswerOptionPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/LoadAnswerOptionsPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/CreateAnswerRangePort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/CreateKitPersisterContext.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/AnswerRangeCreateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/QuestionCreateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/SubjectQuestionnaireCreateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/AnswerRangeCreateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/QuestionCreateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/SubjectQuestionnaireCreateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerRangeMother.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/dsl/AnswerRangeDslModelMother.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/dsl/QuestionDslModelMother.java
=> Fac-810: correct create kit by dsl service due to the adding of answer range model

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentResult.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectValue.java
=> FAC-812: Fix null pointer exception in calculate confidence

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentResult.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectValue.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceServiceTest.java
=> FAC-800 modify confidence level computation algorithm

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.40.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-776: Minor database refactors

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/GetAttributeScoreDetailRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeScoreDetailPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCaseTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/ImpactFullQuestionsView.java
=> FAC-816: add evidence count to get attribute score details service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/CountQuestionEvidenceView.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeQuestionView.java
=> FAC-821: Remove optionImpact from findAttributeScore query

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.40.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.41.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-823 Add 'resolved' field to EvidenceJpaEntity & the table

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/ResolveCommentRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/ResolveCommentUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/ResolveCommentPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/ResolveCommentService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/ResolveCommentUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/ResolveCommentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/EvidenceMother.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
=> FAC-824 Impl comment resolving service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceListUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/LoadEvidencesPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/ResolveCommentService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
=> FAC-825_Refine-get-evidences-service-output

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentDashboardUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
=> AC-839: Rename Objects title in GetAssessmentDashboard Service

flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/users/messages_fa.properties, flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
=> FAC-845: fix - Add Forgotten keys in users module

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/InitAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/InitAssessmentInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/InitAssessmentInsightUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.42.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-841: Implement InitAssessmentInsight service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/CreateAttributeScoresFileAdapter.java
=> FAC-850 Fix-NPE-of-createAttributeAiInsightService

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/ApproveAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinsight/AssessmentInsightMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinsight/AssessmentInsightPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentInsight.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/ApproveAssessmentInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/GetAssessmentInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinsight/ApproveAssessmentInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/ApproveAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/ApproveAssessmentInsightUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/ApproveAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.42.xml
=> FAC-846 Impl approve assessment insight service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaRepository.java
=> FAC-859: prevent negative count in not generated insights count

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
=> FAC-854: Fix - Modify `withoutEvidence` calculating in `GetDashboardBoard` Service

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java
=> FAC-861: return empty insight

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GrantAccessToReportRequestDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GrantAccessToReportRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GrantAccessToReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/GrantAccessToReportUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/UserMother.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC-852 Impl grant access to report service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
=> FAC-867: Fix  `NullPointerException` in `GetKitDsl` service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportServiceTest.java
=> FAC-852 Modify the service & fix tests due to the changes

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/subjectinsight/GetSubjectInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/subjectinsight/GetSubjectInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC-856 Modify get subject insight service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeScoreDetailPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailServiceTest.java
=> FAC-870: Add questionId to GetAttributeScoreDetailService result

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeScoreDetailPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/ImpactFullQuestionsView.java
=> FAC-870: Add questionnaireId to GetAttributeScoreDetailService result

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupJpaRepository.java
=> FAC-851: fix - add status checking to GetExpertGroupList

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListService.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
…nt questionnaire instead of questions
=> FAC-873-fix `countQuestionnairesQuestionsHavingEvidence` query t

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
=> FAC-874:  Fix counting unresolved comments

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetSpaceAssessmentListUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/GetSpaceAssessmentListUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
=> FAC-882: Add `Permissions` object to output of SpaceAssessmentList

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCaseTest.java
=> FAC-876: refactor - Mdify Default Sort and Attribute in AttributeScoreDetails service

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/CreateAttributeInsightRequestDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/CreateAttributeInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/UpdateAttributeInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attributeinsight/CreateAttributeInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/CreateAttributeInsightUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeInsightServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/resources/liquibase/changelog-0.45.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.46.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-880: Modify CreateAttributeInsight api

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.46.xml
=> FAC-885: Create Assessment Report Table and Entity

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitDslRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitdsl/LoadKitDslModelAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/LoadAnswerRangesPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/LoadAttributesPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitdsl/LoadKitDslModelPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/LoadMaturityLevelsPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionsPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadQuestionnairesPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/LoadSubjectsPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDslService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDslServiceTest.java
=> FAC-831 Refactor get dsl ports and adapters

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/CreateAssessmentReportMetadataRequestDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/CreateAssessmentReportMetadataRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/CreateAssessmentReportMetadataUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/CreateAssessmentReportPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/UpdateAssessmentReportPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentreport/CreateAssessmentReportMetadataUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoService.java
=> Fac 886 implement create report metadata api

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentReport.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetSpaceAssessmentListUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJoinResultView.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.46.xml
=> FAC-895: add published to assessment report

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributeinsight/AttributeInsightPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributeinsight/UpdateAttributeInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/GetAttributeInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java
=> FAC-905:fix:Fix GetAttributeInsightService error

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportMetadataUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportMetadataService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportMetadataServiceTest.java
[] - Did you update the corresponding document?
=> FAC-902:Impl:Add published to GetAssessmentReportMetadataUseCase Result

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AttributeReportItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subject/ReportSubjectService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
=> FAC-909: add attribute weight to assessment report

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/subjectinsight/CreateSubjectInsightRestController.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC-855: Add New Endpoint to Create Subject Insight

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/ApproveAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/CreateAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/GetAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/InitAssessmentInsightRestController.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC 904: Add AssessmentInsight new Endpoints

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/adviceitem/AdviceItemPersistenceJpaAdapter.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/adviceitem/AdviceItemJpaRepository.java
=> FAC-910:Impl:Sort advice items in GetAssessmentReportService

.github/workflows/ci-cd.yml
=> FAC-918:hotfix:Fix pipline error for java version

flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/ClassUtil.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/ClassUtils.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentDashboardUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMetadataMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
=> FAC-908: Add Assessment Report Issues to Get Assessment Dashboard Service

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
=> FAC-925: Improve prompt for creating better advice items

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
=> FAC-922:impl:Add order to GetAssessmentReportService's result

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinsight/AssessmentInsightMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinsight/AssessmentInsightPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentInsight.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/CreateAssessmentInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/subjectinsight/CreateSubjectInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinsight/ApproveAssessmentInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/ApproveAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/CreateAssessmentInsightUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/GetAssessmentInsightUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/CreateAttributeAiInsightUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/subjectinsight/CreateSubjectInsightUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/ApproveAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/CreateSubjectInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.47.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.48.xml
=> FAC-916:impl:Add lastModificationTime to AssessmentInsight

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java
=> FAC-913: Refactor Init Assessment

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
=> FAC-917:impl:Count expired insights by lastModificationTime

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/GetAssessmentInsightUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectInsightMother.java
=> FAC-928: Refactor get assessment insight output

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/InvalidStateException.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/api/ErrorCodes.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/InvalidStateExceptionHandler.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AdviceItemMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMetadataMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
=> FAC-923:impl:Check VIEW_REPORT_PREVIEW permission in GetAssessmentReportService

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
=> FAC-926:impl:Add canViewDashboard permission to GetAssessmentReport's result

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/GetAttributeInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeInsightMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectInsightMother.java
=> FAC-929: count unapproved insights in dashboard

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/RestClientConfig.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/RestClientProperties.java
=> FAC-932: Add RestClientConfig and properties to set timeouts

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemListUseCase.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemListService.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemListServiceTest.java
=> FAC-937: Add level code to list of advice items

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/KitLanguage.java, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/kit/KitLanguageTest.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateAssessmentKitUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateKitByDslUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/CreateAssessmentKitPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/UpdateKitInfoPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/CreateKitByDslService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
=> FAC-935:impl:Move KitLanguage enum to common

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/GetAssessmentAttributesRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributeMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAssessmentAttributesUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributesPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributesService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAssessmentAttributesUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/LoadAttributesPort.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributesServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attribute/AttributeMaturityLevelSubjectView.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
=> FAC-924: Implement `GetAssessmentAttributes` Service

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemListUseCase.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/MessageBundle.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/adviceitem/CostLevel.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/adviceitem/ImpactLevel.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/adviceitem/PriorityLevel.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/adviceitem/AdviceItemMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AdviceItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AdviceItemMother.java
=> FAC-938:impl:Enrich AdviceItem fields in GetAssessmentReportUseCase.Result

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/maturitylevel/GetAssessmentMaturityLevelsRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/maturitylevel/GetAssessmentMaturityLevelsUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/maturitylevel/GetAssessmentMaturityLevelsService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/maturitylevel/GetAssessmentMaturityLevelsUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/maturitylevel/GetAssessmentMaturityLevelsServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC-931: Implement Get Assessment Maturity Level

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/SearchKitOptionsUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/SearchKitOptionsUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsServiceTest.java
=> FAC-832: Add isPrivate field to searchKitOption useCase

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/KitLanguage.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/SearchKitOptionsUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
=> FAC-945: Add lang to kit list

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnswerStatus.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CreateAnswerPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnswerStatusTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AnswerJpaEntityMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.48.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.49.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-930:impl:Add status to AnswerJpaEntity

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Answer.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnswerStatus.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/UpdateAnswerPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answerhistory/AnswerHistoryJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.48.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.49.xml
=> FAC-941:impl:Assign status to submitted answer based on CurrentUser role

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
=> FAC-939: Enhance Advice Items Prompt

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answer/SubmitAnswerUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/answer/SubmitAnswerUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
=> FAC-615:impl:Refactor SubmitAnswerService

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppAiProperties.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentKit.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentKitMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
=> FAC-927: Feature : Add the `KitLanguage` as the Language of the `AttributeInsight`

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/ApproveAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/CreateAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/GetAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/InitAssessmentInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/CreateAttributeAiInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/CreateAttributeInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/GetAttributeInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/subjectinsight/CreateSubjectInsightRestController.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC-889: Remove unused insight apis

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/ApproveAllAssessmentInsightsRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributeinsight/AttributeInsightPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectinsight/SubjectInsightPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/ApproveAllAssessmentInsightsUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributeinsight/ApproveAttributeInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subjectinsight/ApproveSubjectInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/ApproveAllAssessmentInsightsService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/ApproveAllAssessmentInsightsUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ApproveAllAssessmentInsightsServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaRepository.java
=> FAC-944:impl:Impl ApproveAllAssessmentInsights service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightServiceTest.java
=> FAC-936: Modify Initial Insights According `KitLanguage`

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitLanguagesRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitLanguagesUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitLanguagesService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitLanguagesServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-951: Implement GetKitLangages service

flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAiAdviceNarrationUseCaseParamTest.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceListUseCase.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/space/GetSpaceListUseCaseParamTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceListServiceTest.java
=> FAC-952: refactor get space list tests

flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetSpaceTypesRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceTypesUseCase.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceTypesService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceTypesServiceTest.java, flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
=> FAC-955: Implement SpaceType List Service

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/tenant/GetTenantRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/tenant/GetTenantUseCase.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/tenant/GetTenantService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/tenant/GetTenantServiceTest.java, flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
=> FAC-481: refactor get tenant api

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java
=> FAC-957:fix:Fix NPE of submitting null answer for existing answer

flickit-assessment-common/src/main/java/org/flickit/assessment/common/validation/EnumValueValidator.java, flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitdsl/GetKitListRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/LoadPublishedKitListPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-953:impl:Support Multi-lang filter in GetKitList service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentDashboardUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CountAnswersPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
=> FAC-959: Add Unapproved Answers to Assessment Dashboard

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/QuestionnaireListItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CountAnswersPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswersQuestionnaireAndCountView.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswersQuestionnairesAndCountView.java
=> FAC-960: Add `unapprovedAnswers` to Questionnaire List

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelper.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelperTest.java
…ionId` in CreateSubjectInsightsHelper
=> FAC-974: Fix InitSubjectInsight BadRequest Problem

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/insight/ApproveExpiredInsightsRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/attribute/AttributeInsightPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/subject/SubjectInsightPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/insight/ApproveExpiredInsightsUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/attribute/ApproveAttributeInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/subject/ApproveSubjectInsightPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/ApproveAllAssessmentInsightsService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/ApproveExpiredInsightsService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/insight/ApproveExpiredInsightsUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/ApproveAllAssessmentInsightsServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/ApproveExpiredInsightsServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/insight/attribute/AttributeInsightJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/insight/subject/SubjectInsightJpaRepository.java
=> FAC-969:impl:Impl ApproveExpiredInsights service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/CreateSpaceRequestDtoMother.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/AbstractScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CheckCreateSpaceScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CreateSpaceScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/DeleteSpaceScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/SpaceTestHelper.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/CheckCreateSpaceRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/CheckCreateSpaceUseCase.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/CountSpacesPort.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CheckCreateSpaceService.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/out/space/CheckCreateSpaceUseCaseParamTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/CheckCreateSpaceServiceTest.java, flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
=> FAC-966: Implement API to Check User Space Creation Limit

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
=> FAC-978:fix:Fix NPE in calculate services

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/ResolveAllCommentsRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/ResolveAssessmentCommentsRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/ResolveAssessmentCommentsUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/ResolveCommentPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/ResolveAssessmentCommentsService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/ResolveAssessmentCommentsUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/ResolveAssessmentCommentsServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
=> FAC-981: Resolve All Assessment Comments Service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/insight/assessment/GetAssessmentOverallInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/insight/attribute/GetAttributeInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/insight/subject/GetSubjectInsightRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/insight/Insight.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/insight/GetAssessmentInsightsUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/GetAssessmentInsightsService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/GetAssessmentInsightsServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/assessment/GetAssessmentInsightHelperTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/attribute/GetAttributeInsightHelperTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/subject/GetSubjectInsightHelperTest.java
=> FAC-977: impl get assessment insights new service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/measure/MeasureJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/measure/MeasureJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/seq/KitDbSequenceGenerators.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.52.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.53.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-985:impl:Add MeasureJpaEntity

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributematurityscore/AttributeMaturityScorePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/insight/GetAssessmentInsightsUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributematurityscore/LoadAttributeMaturityScoresPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/GetAssessmentInsightsService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/GetAssessmentInsightsServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributematurityscore/AttributeMaturityScoreJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributematurityscore/AttributeMaturityScoreView.java
=> FAC-989: add maturity scores to get insights use case

flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/GetAssessmentInsightsServiceTest.java
=> FAC-989: Assert AttributeMaturityScores

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/insight/GetAssessmentInsightsIssuesRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/insight/assessment/GetAssessmentInsightsIssuesUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentInsightsIssuesService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/insight/assessment/GetAssessmentInsightsIssuesUseCaseTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentInsightsIssuesServiceTest.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC-986: Implement Assessment Insights Issues Service

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadQuestionnairesPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/UpdateQuestionnaireOrdersService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/UpdateQuestionnaireOrdersServiceTest.java
=> FAC-992:fix:Fix NPE in UpdateQuestionnaireOrdersService

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRequestDto.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/CreateAssessmentRequestDtoMother.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/UpdateKitInfoRequestDtoMother.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/ScenarioContext.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/AssessmentTestHelper.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/CreateAssessmentErrorScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/CreateAssessmentScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/kit/assessmentkit/KitTestHelper.java
=> FAC-982: Add scenario test for create assessment

flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetSpaceResponseDto.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetSpaceRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceUseCase.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceServiceTest.java
=> FAC-991: Add `canCreateAssessment` Field to LoadSpace Service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/measure/MeasureJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitclone/CloneKitPersistenceJpaAdapter.java
=> FAC-996:impl:Clone measure entities in clone kit service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Question.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/LoadAssessmentQuestionsPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/QuestionAnswerView.java
=> FAC-997: Add measures to graphical report

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/KitLanguage.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/SpringUtil.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitLanguagesService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateAssessmentKitUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateKitByDslUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitLanguagesServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/CreateKitByDslServiceTest.java
=> FAC-998: Add supported kit languages to config

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitlanguage/KitLanguageJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitlanguage/KitLanguageJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.54.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.55.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
=> FAC-1004: Create `Kit Language` Table and Entity

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/measure/MeasureJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.56.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/measure/MeasurePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/measure/LoadMeasurePort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadQuestionnairePort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadQuestionnairesPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/CreateQuestionService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/CreateQuestionnaireService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/DeleteQuestionnaireService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/UpdateQuestionnaireOrdersService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/CreateQuestionServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/CreateQuestionnaireServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/DeleteQuestionnaireServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/UpdateQuestionnaireOrdersServiceTest.java
=> FAC-1023:impl:Remove measure sync changes with questionnaire

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/CreateMeasureRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/CreateMeasureRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/measure/CreateMeasureUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/measure/CreateMeasureService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/measure/CreateMeasureUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/measure/CreateMeasureServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-1026: Implement CreateMeasureService

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Question.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersister.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC1024: Add `measureId` Field to UpdateQuestionUseCase

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionsPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/KitVersionValidator.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/KitVersionValidatorTest.java
=> FAC-1025: Add `Measure` Existence Check in Questions  to KitVersionValidator Service

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitListRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/LoadPublishedKitListPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListServiceTest.java
=> FAC-1028:impl:Make isPrivate optional in GetKitList service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.56.xml
=> FAC-1031: Create `KitBanner` table

flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/JsonUtils.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/validation/EnumValidateUtils.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/CreateAttributeUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/GetAttributesUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/CreateSubjectUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/UpdateSubjectUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetAttributesService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetAttributesServiceTest.java
=> FAC-1032: Add translations to get attributes service

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/KitTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java, flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties, flickit-assessment-common/src/main/resources/i18n/messages_en.properties, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/UpdateKitInfoPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-1020: Add `translations` to UpdateKitService

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.56.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitbanner/GetKitSliderBannersRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitbanner/KitBannerMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitbanner/KitBannerPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/KitBanner.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitbanner/GetKitSliderBannersUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitbanner/LoadKitBannerPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitbanner/LoadKitBannersPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitbanner/GetKitSliderBannersService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitbanner/GetKitSliderBannersUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitbanner/GetKitSliderBannersServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/KitBannerMother.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-1036: Implement GetKitSliderBanners service

flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitlanguage/AddLanguageToKitRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitlanguage/AddLanguageToKitRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitlanguage/KitLanguagePersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitlanguage/AddLanguageToKitUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitlanguage/CreateKitLanguagePort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitlanguage/AddLanguageToKitService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitlanguage/AddLanguageToKitUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitlanguage/AddLanguageToKitServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-1034: impl add lang to kit service

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/GetSubjectListUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/GetSubjectListService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/SubjectQuestionnaireCreateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/SubjectQuestionnaireUpdateKitPersisterTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/GetSubjectListServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/SubjectMother.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-1040: Add Translations to SubjectListService

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitEditableInfoUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
=> FAC-1042:impl:Add translations to get kit editable info service

flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceServiceTest.java
=> FAC-1049: Fix canCreateAssessment condition

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Question.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/GetQuestionnaireQuestionsUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsServiceTest.java
=> FAC-1041: Add Translations to Question List service

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangeMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/measure/MeasureMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnaireMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AnswerOption.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Question.java
=> FAC-1038:impl:Map translations in all mappers used in LoadAssessmentKitFullInfoAdapter

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/maturitylevel/GetKitMaturityLevelsUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/GetKitMaturityLevelsService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/maturitylevel/GetKitMaturityLevelsServiceTest.java
=> FAC-1044:impl:Add translations to GetKitMaturityLevelsService

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/GetMeasuresResponseDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/GetMeasuresRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/measure/MeasureMapper.java
=> FAC-1045:impl:Add translations to GetMeasuresService

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionnaire/GetQuestionnairesResponseDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionnaire/GetQuestionnairesRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
=> FAC-1047:impl:Add translations to GetQuestionnairesService

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AnswerOption.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answeroption/GetQuestionOptionsUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerOptionMother.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-1046_add-translations-to-answerOptions-list-service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
=> FAC-1048:impl:Correct GetKitListService lang filter in JPQLs

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/AnswerOptionTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionTranslation.java, flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/question/LoadQuestionnaireQuestionListPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
=> FAC-1055:impl:Return fields translated in GetAssessmentQuestionnaireQuestionList service

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionnaireTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/SubjectTranslation.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnairePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentResult.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectWithQuestionnaireIdView.java
=> FAC-1056:impl:Return fields translated in GetAssessmentQuestionnaireListService

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/AnswerOptionTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/AttributeTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/KitTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/MaturityLevelTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/MeasureTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionnaireTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/SubjectTranslation.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributematurityscore/AttributeMaturityScorePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/measure/MeasureMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValueMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadSubjectReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/MaturityLevel.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
=> FAC-1058:impl:Return fields translated in GetAssessmentReport service

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRequestDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentKit.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentKitMother.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
=> FAC-1053_add-langId-to-create-assessment-service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryPersistenceJpaAdapter.java
=> FAC-1061:impl:Load answer with translated fields in LoadAnswerHistoryListPort

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/measure/MeasureMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/measure/MeasurePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/measure/LoadMeasuresPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresServiceTest.java
=> FAC-1063:impl:Return fields translated in GetAssessmentAttributeMeasures

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/maturitylevel/LoadMaturityLevelPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/GetAssessmentInsightsService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/assessment/CreateAssessmentInsightHelper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/assessment/InitAssessmentInsightService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/GetAssessmentInsightsServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/assessment/CreateAssessmentInsightHelperTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/assessment/InitAssessmentInsightServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
=> FAC-1064:impl:Return fields translated in InitAssessmentInsight

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributematurityscore/AttributeMaturityScoreMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/ImpactFullQuestionsView.java
=> FAC-1062:impl:Return fields translated in GetAttributeScoreDetail

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributematurityscore/AttributeMaturityScoreMapper.java
=> FAC-1069:fix:Fix NPE error in AttributeMaturityScoreMapper

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/GenerateAllAssessmentInsightsService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeAiInsightHelper.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/GenerateAllAssessmentInsightsServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeAiInsightHelperTest.java
=> FAC-1067:impl:Create insight translated in GenerateAllAssessmentInsights

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsServiceTest.java
=> FAC-1068:impl:Create insight translated in RegenerateExpiredInsights

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributeMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectMapper.java
=> FAC-1070: Translate Attribute Fileds in GetAssessmentAttributesService

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/maturitylevel/LoadMaturityLevelsPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/maturitylevel/GetAssessmentMaturityLevelsService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/maturitylevel/GetAssessmentMaturityLevelsServiceTest.java
=> FAC-1071: Translate MaturityLevel Fileds in GetAssessmentMaturityLevelService

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
=> FAC-1073: Add `Metada` Column to AssessmentKit Table and Entity

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/SearchKitOptionsUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsServiceTest.java
=> FAC-1086:impl:Add languages to KitListItem in SearchKitOptions service

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/KitTranslation.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java, flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties, flickit-assessment-common/src/main/resources/i18n/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRequestDto.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/KitMetadata.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/CreateAssessmentKitPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/UpdateKitInfoPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoService.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-1074: Add `metadata` to UpdateKitInfo Service

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCase.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java
=> FAC-1088: Fix NPE problem in case of deleting metadata

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java
=> FAC-1090:impl:Add languages to GetPublishedKit

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/ImageSize.java, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/kit/ImageSizeTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitbanner/KitBannerMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/KitBanner.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitbanner/GetKitSliderBannersUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitbanner/GetKitSliderBannersService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitbanner/GetKitSliderBannersServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/KitBannerMother.java
X ] - Did you update the corresponding document?
[x] - Did you merge the main branch into this branch recently?
[x] - Did you remove the probable extra code?
[x] - Did you label the PR as 'Ready to Review'?
=> FAC-1091: Support Multiple Kit Banners Sizes

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
=> FAC-1095:fix:Fix 404 error of GetAssessmentService

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitcustom/GetKitCustomSubjectUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitcustom/GetKitCustomSubjectService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/GetKitCustomSubjectServiceTest.java
=> FAC-1094:impl:Return translations of results in GetKitCustomSubject

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentReport.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/VisibilityType.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/UpdateAssessmentReportPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/VisibilityTypeTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml
=> FAC-1105: add visibility type to update assessment report publish status service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/VisibilityType.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/VisibilityTypeTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml
=> FAC-1099: Add is VisibilityType field to AssessmentReportTable

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentResponseDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
=> FAC-1108:impl:Add assessment language to GetAssessmentService result

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
=> FAC-1109: Add visibility to result

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetPublishedKitRestController.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java, flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
=> FAC-1111: Implement Public API for GetAssessmentKit

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCaseParamTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/ExpertGroupMother.java
=> FAC-1112: Add expertgroup to get assessment kit use case

.github/workflows/ci-cd.yml
=> FAC-1120:impl: Edit deploy job

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentMode.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/CreateAssessmentPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentModeTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AssessmentJpaEntityMother.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.59.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-1121: Add `mode` to assessment

flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/JsonUtils.java
=> FAC-1124: Handle Json null values in JsonUtils

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentResponseDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Assessment.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentMode.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentModeTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
=> FAC-1126: Add assessment mode to GetAssessmentService

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetSpaceAssessmentListUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
=> FAC-1127: Add assessment `mode` to GetSpaceAssessments service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentPublicReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentPublicReportService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentPublicReportServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
=> FAC-1131: Add assessment `mode`  to GraphicalReportServices

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/GenerateAllAssessmentInsightsService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/GenerateAllAssessmentInsightsServiceTest.java
=> FAC-1129: Use Insight Helper in GenerateAllAssessmentInsightsService

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsServiceTest.java
=> FAC-1130: Use RegenerateExpiredInsightsHelper in RegenerateExpiredInsightsService

.github/pull_request_template.md, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/AssessmentTestHelper.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/DeleteSpaceScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/GetSpaceScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/SpaceTestHelper.java
=> FAC-1050: Implement `GetSpaceService` System Test

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/adviceitem/AdviceItemPersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/advicenarration/AdviceNarrationPersistenceJpaAdapter.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/adviceitem/LoadAdviceItemPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/advicenarration/LoadAdviceNarrationPort.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/RefreshAssessmentAdviceService.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/RefreshAssessmentAdviceServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/adviceitem/AdviceItemJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/advicenarration/AdviceNarrationJpaRepository.java
=> FAC-1150: Add Advice Existance Constraint Refresh Advice Service

flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/users/messages_fa.properties, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetTopSpacesRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetTopSpacesUseCase.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/LoadSpaceListPort.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetTopSpacesService.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/MessageKey.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/space/GetTopSpacesUseCaseParamTest.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetTopSpacesServiceTest.java, flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
=> FAC-1145: Implemet TopSpacesService

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/constraint/AssessmentCoreDataConstraintErrorMapper.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.59.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.60.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/CreateAssessmentErrorScenarioTest.java
=> FAC-1141: Remove Assessment Title Uniqueness Constraint

flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetTopSpacesRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetTopSpacesUseCase.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetTopSpacesService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetTopSpacesServiceTest.java
=> FAC-1159: Put returned spaces from TopSpacesService to `items` key

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaEntity.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.60.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-0.61.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
=> FAC-1153: Add `Price` Column to AssessmentKit table

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
=> FAC-1154: Add `isFree` to GetPublishedKit usecase

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/KitWithExpertGroupView.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kittag/KitTagJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kittag/KitTagPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/LoadPublishedKitListPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kittag/LoadKitTagListPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListServiceTest.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublicKitListServiceTest.java
=> FAC-1158: Add `IsFree` and `hasAccess` to GetKitList

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/attribute/AttributeMapper.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/Attribute.java, flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/RefreshAssessmentAdviceService.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationHelperTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/RefreshAssessmentAdviceServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AttributeMother.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/MaturityLevelMother.java
=> FAC-1187: Modify Attribute Maturity Level Target Calculation in Refresh Advice Service

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportMetadataService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportMetadataServiceTest.java
=> FAC-1192: Handle NPE in GetReportMetadata Service

flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java, flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
=> FAC-1190: Add CALCULATE_ASSESSMENT permission to ReportViewer Role

flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/GetTopSpacesScenarioTest.java, flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/SpaceTestHelper.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetTopSpacesResponseDto.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetTopSpacesRestController.java, flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetTopSpacesService.java, flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetTopSpacesServiceTest.java
=> FAC-1152: Implement Scenario Test for TopSpacesService

flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationHelper.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationHelperTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java, flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AssessmentMother.java, flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppAiProperties.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeAiInsightHelper.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeAiInsightHelperTest.java
=> FAC-1199: Remove Assessment Title from Prompts

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/seq/KitDbSequenceGenerators.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/usersurvey/UserSurveyJpaEntity.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/usersurvey/UserSurveyJpaRepository.java, flickit-assessment-data/src/main/resources/liquibase/changelog-0.63.xml, flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
=> FAC-1203: Create UseSurveyTable

flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppAiProperties.java
=> FAC-1209: Remove the extra parts of the prompts

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentPublicReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentPublicReportService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentPublicReportServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
=> FAC-1210: Add `isAdvisable` Filed to report services (Public and Non-Public)

flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/question/LoadQuestionPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentNextQuestionnaireService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentNextQuestionnaireServiceTest.java, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
=> FAC-1208_add-nextQuestionIndexField-to-nextQuestionnaireService

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataServiceTest.java
=> FAC-1215: Handle null metadata in CreateAssessmentReportMetadataService

flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataServiceTest.java
=> FAC-1221: Fix Metadata Update in CreateAssessmentReportMetadataService

flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties, flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/measure/GetAttributeMeasureQuestionsResponseDto.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/measure/GetAttributeMeasureQuestionsRestController.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/measure/GetAttributeMeasureQuestionsUseCase.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeQuestionsPort.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/measure/GetAttributeMeasureQuestionsService.java, flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/measure/GetAttributeMeasureQuestionsUseCaseParamTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/measure/GetAttributeMeasureQuestionsServiceTest.java, flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionMother.java, flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json, flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
=> FAC-1234: Implement AssessmentAttributeMeasureQuestions Service

flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaRepository.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionPersistenceJpaAdapter.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitEditableInfoUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitversion/LoadKitVersionPort.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoServiceTest.java
=> FAC-1265: Add `draftVersionId` to `GetKitEditableInfo` Service

flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitDetailUseCase.java, flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDetailService.java, flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDetailServiceTest.java
=> FAC-1267: Add `attributes` to subjects of GetKitDetailUseCase

.github/workflows/ci-cd.yml
=> Fac 1250 remove sonar from releases
